apiVersion: v1
kind: Service
metadata:
  name: ragops-service
  namespace: default
spec:
  selector:
    app: ragops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort